package com.levmin.nginxtest.entry;

import java.util.Date;

public class UserAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.id
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.username
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.password
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.email
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.phone
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.status
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.create_time
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.update_time
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.id
     *
     * @return the value of user_account.id
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.id
     *
     * @param id the value for user_account.id
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.username
     *
     * @return the value of user_account.username
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.username
     *
     * @param username the value for user_account.username
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.password
     *
     * @return the value of user_account.password
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.password
     *
     * @param password the value for user_account.password
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.email
     *
     * @return the value of user_account.email
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.email
     *
     * @param email the value for user_account.email
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.phone
     *
     * @return the value of user_account.phone
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.phone
     *
     * @param phone the value for user_account.phone
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.status
     *
     * @return the value of user_account.status
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.status
     *
     * @param status the value for user_account.status
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.create_time
     *
     * @return the value of user_account.create_time
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.create_time
     *
     * @param createTime the value for user_account.create_time
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.update_time
     *
     * @return the value of user_account.update_time
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.update_time
     *
     * @param updateTime the value for user_account.update_time
     *
     * @mbg.generated Sun Jan 18 02:11:57 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}